<?php
$z[0]=Array("field","逍遥医生,逍遥医生下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《逍遥医生》高清下载,《逍遥医生》全集高清快播_百度影音在线观看下载,包含《逍遥医生》3GP MP4下载,下载《逍遥医生》高清电视剧就上7060.COM",74,339);
$z[1][4]['name']="description";
$z[2]=Array("field","逍遥医生",341,391);
$z[2][4]['name']="title";
$z[3]=Array("field","",393,432);
$z[3][4]['name']="writer";
$z[4]=Array("field","",434,473);
$z[4][4]['name']="source";
$z[5]=Array("field","乔纳森·莱文",475,531);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 11:25",533,583);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",585,628);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",630,674);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",676,713);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",715,753);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","William Rush医生（Tom Ellis）是一个出诊医生，但是他不属于任何一家医院。他对病人极为挑剔，不达到他的要求他绝不上门。他要求病人必须支付数目不菲的现金酬劳，而且他看完病就举办花天酒地的聚会。他声称自己对这些「不干净」的客户从不做出评价，但他无法对那些丑恶的现象做到百分之百「免疫」。他无意改变自己的生活方式——直到一个老情人突然出现，引起他对良知和道德感的思考。《逍遥医生》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",755,1419);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1421,1461);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","汤姆·艾利斯,莎拉·哈贝尔,奥黛塔·安纳布尔,Cindy Busby,布莱恩·马克金森,Angell Conwell,基诺·安东尼·佩西,Teach Grant,罗兰多·莫利纳,Emily Bruhn,Arlina Rodriguez,Cesar Ventura,Rebecca Olson",1463,1728);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-08/53e1e0166c7d7.jpg",1730,1828);
$z[14][4]['name']="litpic";

?>