{dede:field name='keywords'}神秘博士 第八季,神秘博士{/dede:field}
{dede:field name='description'}7060手机电视剧为您提供《神秘博士 第八季》高清下载,《神秘博士 第八季》全集高清快播_百度影音在线观看下载,包含《神秘博士 第八季》3GP MP4下载,下载《神秘博士 第八季》高清电视{/dede:field}
{dede:field name='title'}神秘博士 第八季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='daoyan'}{/dede:field}
{dede:field name='niandai'}2014 13:01{/dede:field}
{dede:field name='diqu'}欧美{/dede:field}
{dede:field name='yuuan'}英语{/dede:field}
{dede:field name='pfz'}0{/dede:field}
{dede:field name='pfrs'}0{/dede:field}
{dede:field name='juqing'}<p>BBC于2013年8月4日宣布彼得·卡帕尔蒂接任博士，将在2013年圣诞篇中取代马特·史密斯重生为第12任doctor。</p>
<p>第八季其总编剧依然为史蒂芬·莫法特。</p>《神秘博士 第八季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='zhuyan'}马特·史密斯,彼得·卡帕尔蒂{/dede:field}
{dede:field name='litpic'}http://p.tao30.com/Upload-s/video/2014-09/5404280a77778.jpg{/dede:field}
