<?php
$z[0]=Array("field","暴君,暴君下载,暴君快播",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《暴君》高清下载,《暴君》全集高清快播_百度影音在线观看下载,包含《暴君》3GP MP4下载,下载《暴君》高清电视剧就上7060.COM",75,316);
$z[1][4]['name']="description";
$z[2]=Array("field","暴君",318,362);
$z[2][4]['name']="title";
$z[3]=Array("field","",364,403);
$z[3][4]['name']="writer";
$z[4]=Array("field","",405,444);
$z[4][4]['name']="source";
$z[5]=Array("field","大卫·叶茨",446,499);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 14:15",501,551);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",553,596);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",598,642);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",644,681);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",683,721);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","《<b>暴君</b>》是一个颇像反恐剧《国土安全》与间谍剧《美国人》结合的新剧，讲述了一个表面本分的美国家庭，卷入了一场中东国家混乱风波的故事。该剧的幕后主创恰恰是打造《国土安全》的霍华德·高登、吉迪昂·拉夫以及《迷失》的克雷格·奈特。《暴君》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",723,1190);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1192,1232);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","詹妮佛·芬尼甘,莫兰·阿提艾斯,Ashraf Barhom,Anne Winters,萨米·谢伊克,Noah Silver,麦赫迪·德比,Sophia Taylor Ali,Cameron Gharaee,Sibylla Deen,Amine El Bnouhi",1234,1452);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-06/53ae46c8c1317.jpg",1454,1552);
$z[14][4]['name']="litpic";

?>