
<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:daoyan>

<field:zhuyan itemname="主演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuyan>

<field:niandai itemname="年代" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="2010,2011,2012,2013,2014,2015"  maxlength="250" page="">
</field:niandai>
