<?php
$z[0]=Array("field","陨落星辰 第四季,陨落星辰",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《陨落星辰 第四季》高清下载,《陨落星辰 第四季》全集高清快播_百度影音在线观看下载,包含《陨落星辰 第四季》3GP MP4下载,下载《陨落星辰 第四季》高清电视",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","陨落星辰 第四季",368,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","",512,551);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 17:11",553,603);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",605,648);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",650,694);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",696,733);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",735,773);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","<p>TNT宣布续订《陨落星辰》（Falling Skies）第四季，订数仍然为10集。该剧第三季平均观众人数（Live+7）为580万。</p>\r\n<p>在第四季中，Tom Mason和他领导的第二独立团决心一劳永逸地击败入侵地球的外星人，夺回属于人类的家园。</p>《陨落星辰 第四季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",775,1222);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1224,1264);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","Treva Etienne,Dakota Daulby,马克西·奈特,Nicole LaPlaca,David Raynolds,Desiree Ross",1266,1393);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-06/53ae4ccd0f087.jpg",1395,1493);
$z[14][4]['name']="litpic";

?>