<?php
$z[0]=Array("field","哈哈大校,哈哈大校下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《哈哈大校》高清下载,《哈哈大校》全集高清快播_百度影音在线观看下载,包含《哈哈大校》3GP MP4下载,下载《哈哈大校》高清电视剧就上7060.COM",74,339);
$z[1][4]['name']="description";
$z[2]=Array("field","哈哈大校",341,391);
$z[2][4]['name']="title";
$z[3]=Array("field","",393,432);
$z[3][4]['name']="writer";
$z[4]=Array("field","",434,473);
$z[4][4]['name']="source";
$z[5]=Array("field","MattLipsey",475,524);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 10:33",526,576);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",578,621);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",623,667);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",669,706);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",708,746);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","The story is set in a high school senior colonel, \"ha ha\" focusing is a group of eccentric art teacher, wishful thinking of love, as well as their daily teaching work of many funny plot... Chemistry teacher Chach (David Walliams) madly in love with the new French teacher wave Easton (Catherine Tate), and physical education teacher Genn (Philip Glenister) is a dandy, he obviously will not stand idly by.&nbsp;《哈哈大校》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",748,1295);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1297,1337);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","David Walliams,Catherine Tate,Steve Speirs,James Greene,Frances de la Tour",1339,1452);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-08/5402c05c3f89f.jpg",1454,1552);
$z[14][4]['name']="litpic";

?>