{dede:noteinfo notename="电影采集" channelid="17" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.7060.la/list/23_0_46_0_0_0_new_(*).html"
startid="5" endid="6" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div id="haibaoBox">{/dede:areastart}
    {dede:areaend}<div class="pager">{/dede:areaend}
{/dede:listrule}
