<?php
$z[0]=Array("field","逍遥法外,逍遥法外下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《逍遥法外》高清下载,《逍遥法外》全集高清快播_百度影音在线观看下载,包含《逍遥法外》3GP MP4下载,下载《逍遥法外》高清电视剧就上7060.COM",74,339);
$z[1][4]['name']="description";
$z[2]=Array("field","逍遥法外",341,391);
$z[2][4]['name']="title";
$z[3]=Array("field","",393,432);
$z[3][4]['name']="writer";
$z[4]=Array("field","",434,473);
$z[4][4]['name']="source";
$z[5]=Array("field","",475,514);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 13:14",516,566);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",568,611);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",613,657);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",659,696);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",698,736);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","是一部带有强烈悬疑色彩的剧集，被称作「律政惊悚剧」。该剧由《实习医生格蕾》（Grey’s Anatomy）和《丑闻》（Scandal）的制片人Shonda Rhimes及其制片公司Shondaland策划，这是该公司今年卖出的第四个新项目（同时也是该公司第二部以黑人女性为头号主角的剧集）。故事描述一群满怀抱负的法学院学生和神秘的犯罪辩护学教授Annalise DeWitt（Viola Davis）卷入一场谋杀阴谋，导致他们所有人的生活被彻底改变。DeWitt不仅教学，还是一位著名的刑事案件诉讼律师。她聪明、热情、迷人、有创意，在法庭上和课堂里均冷酷无情。她很善于操纵别人，特别是她的学生。她亲自挑选了几名最优秀的学生到自己的事务所打工。她与一位心理学教授结了婚，但却保持着一段绝不能让第三人知道的婚外情。《逍遥法外》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",738,1789);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1791,1831);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","维奥拉·戴维斯,Matt McGorry,凯蒂·芬德莱,卡拉·苏扎",1833,1938);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-10/54322c9eec178.jpg",1940,2038);
$z[14][4]['name']="litpic";

?>