<?php
$z[0]=Array("field","背包客,背包客下载,背包客",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《背包客》高清下载,《背包客》全集高清快播_百度影音在线观看下载,包含《背包客》3GP MP4下载,下载《背包客》高清电视剧就上7060.COM",78,331);
$z[1][4]['name']="description";
$z[2]=Array("field","背包客",333,380);
$z[2][4]['name']="title";
$z[3]=Array("field","",382,421);
$z[3][4]['name']="writer";
$z[4]=Array("field","",423,462);
$z[4][4]['name']="source";
$z[5]=Array("field","JoshLevy",464,511);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 15:32",513,563);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",565,608);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",610,654);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",656,693);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",695,733);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","CW准备在其数字平台CW Seed上播出10集夏季新剧《<b>背包客</b>》（Backpackers）。故事描述好朋友Ryan（Noah Reid）和Brandon（Dillon Casey）穿越欧洲寻找Ryan失踪的未婚妻，同时「追寻人生的正确方向」。CW Seed此前已经发布过一部分视频，这些视频在经过重新整理后将当做新剧的前四集，后六集会择期进行拍摄。具体播出时间待定。《背包客》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",735,1294);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1296,1336);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","诺亚.雷德,迪隆·凯西,Mishael Morgan,Nils Hognestad,Aurélie Montea,梅根·赫弗恩",1338,1469);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-07/53ca14f3d73d7.jpg",1471,1569);
$z[14][4]['name']="litpic";

?>