<div class="movie_tui">
						<div class="movie_tui_pic"><a href="#" target="_blank"><img alt="山楂树之恋" src="{dede:global.cfg_templets_skin/}/images/movietui/shanzhashu.jpg" /></a></div>
						<h4><a href="#" target="_blank">推荐电影：《》</a></h4>
						<span>导演：<a href="#" target="_blank">张艺谋</a>主演：<a href="#" target="_blank">周冬雨</a>年代：<a href="#" target="_blank">2010</a></span>
						<p>这是一个发生在二十世纪七十年代初期的初恋故事。故事女主人公静秋是城市即将高中毕业的学生。她跟随教育革命实践小组来到一个名叫西坪村的地方，采集革命传统故事……</p>
					</div>