<?php
$z[0]=Array("field","记忆神探 第三季,记忆神探",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《记忆神探 第三季》高清下载,《记忆神探 第三季》全集高清快播_百度影音在线观看下载,包含《记忆神探 第三季》3GP MP4下载,下载《记忆神探 第三季》高清电视",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","记忆神探 第三季",368,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","",512,551);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 17:09",553,603);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",605,648);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",650,694);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",696,733);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",735,773);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","<div><br />",775,825);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",827,867);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","波普伊·蒙哥马利,迪伦·沃尔什,简·库丁",869,961);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-07/53bd1a4056e03.jpg",963,1061);
$z[14][4]['name']="litpic";

?>