<?php
$z[0]=Array("field","海军罪案调查处,第十二季",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《海军罪案调查处 第十二季》高清下载,《海军罪案调查处 第十二季》全集高清快播_百度影音在线观看下载,包含《海军罪案调查处 第十二季》3GP MP4下载,下载《",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","海军罪案调查处  第十二季",366,439);
$z[2][4]['name']="title";
$z[3]=Array("field","",441,480);
$z[3][4]['name']="writer";
$z[4]=Array("field","",482,521);
$z[4][4]['name']="source";
$z[5]=Array("field","TonyWharmby",523,573);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 10:23",575,625);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",627,670);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",672,716);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",718,755);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",757,795);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","CBS一口气续订18部剧集，其中包括《海军犯罪调查处》。《海军罪案调查处  第十二季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",797,1030);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1032,1072);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","马克·哈蒙,迈克尔·韦瑟利,蔻特·德·帕布罗,宝蕾·佩雷特,尚恩·穆雷,洛奇·卡罗尔,大卫·麦考姆,布莱恩·迪岑",1074,1258);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-10/54449f3bd8cb1.jpg",1260,1358);
$z[14][4]['name']="litpic";

?>