{dede:field name='keywords'}与世隔绝,与世隔绝下载{/dede:field}
{dede:field name='description'}7060手机电视剧为您提供《与世隔绝》高清下载,《与世隔绝》全集高清快播_百度影音在线观看下载,包含《与世隔绝》3GP MP4下载,下载《与世隔绝》高清电视剧就上7060.COM{/dede:field}
{dede:field name='title'}与世隔绝{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='daoyan'}Kevin Tancharoen古桑{/dede:field}
{dede:field name='niandai'}2014 14:24{/dede:field}
{dede:field name='diqu'}欧美{/dede:field}
{dede:field name='yuuan'}英语{/dede:field}
{dede:field name='pfz'}0{/dede:field}
{dede:field name='pfrs'}0{/dede:field}
{dede:field name='juqing'}<p>州长八岁大的儿子惨遭谋杀。年轻有为的律师丹尼·弗明为被告辩护，却发现案情背后内有玄机。事关重大，法官宣布让12名陪审团成员住进严密封锁的酒店，对案情进行讨论。情况却愈发扑朔迷离，挑战着所有人的道德底线。陪审团成员之一安娜必须在她的信念及家人的安全中做出抉择，决定一个可能无辜之人的生死。</p>
<p>本剧为索尼下属视频网站Crackle的原创电视剧集，该台其他著名作品有杰瑞·宋飞主演的艾美奖提名剧集《谐星乘车买咖啡》，以及《英雄》主演米洛·文堤米利亚执行制作并参演的《杀无赦》。</p>《与世隔绝》电视剧全集下载百度影音在线观看由7060手机电影收集整理。{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='zhuyan'}莎莫·格劳,杰西·布拉德福特,帕特里克·沃伯顿{/dede:field}
{dede:field name='litpic'}http://p.tao30.com/Upload-s/video/2014-10/5444aa4221dc9.jpg{/dede:field}
