<li class="d[field:global.cfg.autoindex/]"><a href="[field:arcurl/]" target="_blank"><img  src="[field:litpic/]" alt="爱情维修站 3GP MP4高清下载" /></a><p>[field:yuuan/]</p><b><a href="www.a67.com/movie/7989" target="_blank">[field:title/]</a><img src="[field:global.cfg_templets_skin/]/images/1.jpg"><em>[field:pfz/]分</em></b></li> 
             {dede:arclist}	 
			</div>
			<div class="movie_txt">
				<ul>
					<li><span><a href="#" target="_blank">昨天更新</a> |</span><a href="#" target="_blank">鱼狗</a><a href="#" target="_blank">卑鄙的我</a><a href="#" target="_blank">爱出色</a><a href="#" target="_blank">群魔乱舞</a><a href="#" target="_blank">我的野蛮男友</a><a href="#" target="_blank">河东狮吼</a><a href="#" target="_blank">朋党</a><a href="#" target="_blank">凶榜</a><a href="#" target="_blank">恭喜发财</a><a href="#" target="_blank">床上的故事</a></li>
					<li><span><a href="#" target="_blank">前天更新</a> |</span><a href="#" target="_blank">露西娅的情人</a><a href="#" target="_blank">珍珠港</a><a href="#" target="_blank">黑白战场</a><a href="#" target="_blank">小生怕怕</a><a href="#" target="_blank">另一个大仲马</a><a href="#" target="_blank">绑匪</a><a href="#" target="_blank">瘦虎肥龙</a><a href="#" target="_blank">刺马</a><a href="#" target="_blank">爱与诚</a><a href="#" target="_blank">性与早餐</a></li>
					<li><span><a href="#" target="_blank">12-2更新</a> |</span><a href="#" target="_blank">爱我别走</a><a href="#" target="_blank">爱杀2000</a><a href="#" target="_blank">爱情敏感地带</a><a href="#" target="_blank">热血最强</a><a href="#" target="_blank">爱情维修站</a><a href="#" target="_blank">屠龙少年历险记</a><a href="#" target="_blank">四三二一</a><a href="#" target="_blank">双重时间</a><a href="#" target="_blank">电锯惊魂7</a><a href="#" target="_blank">铁男3：子弹人</a></li>
				</ul>
			</div>
		</div>
		<div class="paihang">
		<div class="paihang_top">上升最快</div>
			<div class="paihang_u">
   				<ul class="block">
					<li class="hover"><span>1</span><a href="/movie/7036" title="金瓶双艳3GP MP4下载" target="_blank">金瓶双艳</a></li> 
					<li class="hover"><span>2</span><a href="/movie/7238" title="生化危机4：来生3GP MP4下载" target="_blank">生化危机4：来生</a></li> 
					<li class="hover"><span>3</span><a href="/movie/7623" title="钻石狗3GP MP4下载" target="_blank">钻石狗</a></li> 
					<li><span>4</span><a href="/movie/7634" title="世界大战3GP MP4下载" target="_blank">世界大战</a></li> 
					<li><span>5</span><a href="/movie/7583" title="女教师日记3GP MP4下载" target="_blank">女教师日记</a></li> 
					<li><span>6</span><a href="/movie/7676" title="子曰：食色性也3GP MP4下载" target="_blank">子曰：食色性也</a></li> 
					<li><span>7</span><a href="/movie/7566" title="在床上3GP MP4下载" target="_blank">在床上</a></li> 
					<li><span>8</span><a href="/movie/5727" title="2012末日预言3GP MP4下载" target="_blank">2012末日预言</a></li> 
					<li><span>9</span><a href="/movie/7602" title="顶层公寓3GP MP4下载" target="_blank">顶层公寓</a></li> 
					<li class="none"><span>10</span><a href="/movie/5335" title="海云台3GP MP4下载" target="_blank">海云台</a></li> 
				</ul>	
 		</div>
		</div>
	</div>
	<div class="module">
		<div class="movie">
			<div class="movie_top"><span>热门大片</span><p><a href="#" title="热门手机电影" target="_blank">更多>></a></p></div>	
			<div class="movie_list">
				<li class="d1"><a href="www.a67.com/movie/7448" target="_blank"><img alt="狄仁杰之通天帝国" src="img.a67.com/2010/10/128744929407f2.jpg" /></a><p>国语</p><b><a href="www.a67.com/movie/7448" target="_blank">狄仁杰之通天帝国</a><img src="{dede:global.cfg_templets_skin