<?php
$z[0]=Array("field","大西洋帝国 第五季,大西洋",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《大西洋帝国 第五季》高清下载,《大西洋帝国 第五季》全集高清快播_百度影音在线观看下载,包含《大西洋帝国 第五季》3GP MP4下载,下载《大西洋帝国 第五季》",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","大西洋帝国 第五季",368,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","蒂姆·范·帕腾",515,573);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 12:03",575,625);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",627,670);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",672,716);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",718,755);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",757,795);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","HBO确认《大西洋帝国》（Boardwalk Empire）第五季将是该剧的最后一季，HBO的项目主管称该剧必将有一个「令人兴奋的」结局。《大西洋帝国 第五季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",797,1109);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1111,1151);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","史蒂夫·布西密",1153,1212);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/54191c1ebaa2c.jpg",1214,1312);
$z[14][4]['name']="litpic";

?>