<?php
$z[0]=Array("field","入侵者,入侵者下载,入侵者",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《入侵者》高清下载,《入侵者》全集高清快播_百度影音在线观看下载,包含《入侵者》3GP MP4下载,下载《入侵者》高清电视剧就上7060.COM",78,331);
$z[1][4]['name']="description";
$z[2]=Array("field","入侵者",333,380);
$z[2][4]['name']="title";
$z[3]=Array("field","",382,421);
$z[3][4]['name']="writer";
$z[4]=Array("field","",423,462);
$z[4][4]['name']="source";
$z[5]=Array("field","GlenMorgan",464,513);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 14:02",515,565);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",567,610);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",612,656);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",658,695);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",697,735);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","BBC确认科幻剧《<b>入侵者</b>》（Intruders）将在8月23日播出。该剧根据2007年出版的同名小说改编，由来自《X档案》的一名编剧负责创作，与“万能钥匙”架构类似。故事描述一个秘密社团找到了永生的秘密——他们可以将自己的灵魂跳到别人的躯体里，利用别人的躯体充当「庇护所」。《入侵者》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",737,1248);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1250,1290);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","约翰·西姆,米拉·索维诺,詹姆斯·弗莱恩,Tory Kittles,Karin Konoval,Millie Bobby Brown",1292,1430);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/5404273af2c53.jpg",1432,1530);
$z[14][4]['name']="litpic";

?>