<?php
$z[0]=Array("field","假亦真 第二季,假亦真 第",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《假亦真 第二季》高清下载,《假亦真 第二季》全集高清快播_百度影音在线观看下载,包含《假亦真 第二季》3GP MP4下载,下载《假亦真 第二季》高清电视剧就上",76,361);
$z[1][4]['name']="description";
$z[2]=Array("field","假亦真 第二季",363,420);
$z[2][4]['name']="title";
$z[3]=Array("field","",422,461);
$z[3][4]['name']="writer";
$z[4]=Array("field","",463,502);
$z[4][4]['name']="source";
$z[5]=Array("field","JamieTravis",504,554);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 11:19",556,606);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",608,651);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",653,697);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",699,736);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",738,776);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","MTV宣布续订同性恋剧集《假亦真》（Faking It）第二季10集。《假亦真 第二季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",778,998);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1000,1040);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","Rita Volk,Katie Stevens,Gregg Sulkin,Bailey Buntain,Michael J. Willett",1042,1151);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/542505cca5f27.jpg",1153,1251);
$z[14][4]['name']="litpic";

?>