<?php
$z[0]=Array("field","傲骨贤妻 第六季,傲骨贤妻",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《傲骨贤妻 第六季》高清下载,《傲骨贤妻 第六季》全集高清快播_百度影音在线观看下载,包含《傲骨贤妻 第六季》3GP MP4下载,下载《傲骨贤妻 第六季》高清电视",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","傲骨贤妻 第六季",368,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","布鲁克·肯尼迪",512,571);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 11:34",573,623);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",625,668);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",670,714);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",716,753);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",755,793);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","CBS一口气续订18部剧集，其中包括《傲骨贤妻》。《傲骨贤妻 第六季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",795,1006);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1008,1048);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","朱丽安娜·,艾伦·卡明,克里斯·诺斯,雅奇·潘嘉比,马克·沃伦,乔西·查尔斯,克里斯汀·芭伦斯基,马特·朱克瑞",1050,1232);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/5424dd25b5fe9.jpg",1234,1332);
$z[14][4]['name']="litpic";

?>