
<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:daoyan>

<field:zhuyan itemname="主演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuyan>

<field:niandai itemname="年代" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="2010,2011,2012,2013,2014,2015"  maxlength="250" page="">
</field:niandai>

<field:diqu itemname="地区" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="大陆,欧美,日韩,港台,其他"  maxlength="250" page="">
</field:diqu>

<field:yuuan itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="国语,英语,韩语,粤语"  maxlength="250" page="">
</field:yuuan>

<field:pfz itemname="评分值" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="200" page="">
</field:pfz>
