<?php
$z[0]=Array("field","女孩成长记,女孩成长记下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《女孩成长记》高清下载,《女孩成长记》全集高清快播_百度影音在线观看下载,包含《女孩成长记》3GP MP4下载,下载《女孩成长记》高清电视剧就上7060.COM",77,354);
$z[1][4]['name']="description";
$z[2]=Array("field","女孩成长记",356,409);
$z[2][4]['name']="title";
$z[3]=Array("field","",411,450);
$z[3][4]['name']="writer";
$z[4]=Array("field","",452,491);
$z[4][4]['name']="source";
$z[5]=Array("field","",493,532);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 11:27",534,584);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",586,629);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",631,675);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",677,714);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",716,754);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","<div><br />",756,806);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",808,848);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","罗温·布兰查德,Sabrina Carpenter,丹妮拉·费舍,Teo Halm,Peyton Meyer,Ben Savage",850,978);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-07/53b4e2a883530.jpg",980,1078);
$z[14][4]['name']="litpic";

?>