<?php
$z[0]=Array("field","实习医生格蕾,第十一季",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《实习医生格蕾 第十一季》高清下载,《实习医生格蕾 第十一季》全集高清快播_百度影音在线观看下载,包含《实习医生格蕾 第十一季》3GP MP4下载,下载《实习医",74,361);
$z[1][4]['name']="description";
$z[2]=Array("field","实习医生格蕾 第十一季",363,432);
$z[2][4]['name']="title";
$z[3]=Array("field","",434,473);
$z[3][4]['name']="writer";
$z[4]=Array("field","",475,514);
$z[4][4]['name']="source";
$z[5]=Array("field","ShondaRhimes",516,567);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 13:06",569,619);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",621,664);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",666,710);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",712,749);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",751,789);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","Cristina离去之后，Maggie Pierce医生（Kelly McCreary）来到了「Grey-Sloan纪念医院」。与此同时，Derek似乎已经下定决心要到华盛顿去工作。Meredith试图在家中和医院里同时表现得「一如常态」，但生活中的诸多变化还是让她感觉难以承受。Callie和Arizona对代孕一事达成共识。Amelia偶然听到一个大秘密。Bailey意识到自己必须为Alex争取Cristina留下的医院董事会席位。一场可怕的事故导致两名青少年陷入糟糕的情形。《实习医生格蕾 第十一季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",791,1479);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1481,1521);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","艾伦·旁派,帕特里克·德姆西,贾斯汀·钱伯斯,钱德拉·威尔森,小詹姆斯·皮肯斯,莎拉·拉米尔兹,Jerrika Hinton,卡米拉·卢丁顿",1523,1723);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/5428cb1b6935a.jpg",1725,1823);
$z[14][4]['name']="litpic";

?>