<?php
$z[0]=Array("field","唐顿庄园 第五季,唐顿庄园",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《唐顿庄园 第五季》高清下载,《唐顿庄园 第五季》全集高清快播_百度影音在线观看下载,包含《唐顿庄园 第五季》3GP MP4下载,下载《唐顿庄园 第五季》高清电视",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","唐顿庄园 第五季",368,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","布莱恩·派西维尔",512,574);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 10:05",576,626);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",628,671);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",673,717);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",719,756);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",758,796);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","在第五季开始，当地人准备建立一座战争纪念碑，但是Carson和Robert、Hughes夫人发生了矛盾。Jimmy吸引了一些女性的关注，结果给他带来了大问题。Baxter被迫面对一个最后通牒。Tom与Sarah的友谊快速发展，这引发了Robert的担忧。Mary已经做好了再次寻找爱情的准备。Edith和Drewe的特别安排可能彻底崩溃，因为她越来越不能控制自己的感情，这给每个人都带来了灾难性的后果。《唐顿庄园 第五季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",798,1433);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1435,1475);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","休·博内威利,米歇尔·道克瑞,伊丽莎白·麦戈文,索菲,朱利安·欧文登,Richard E. Grant,Anna Chancellor,Rade Sherbedgia",1477,1655);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-10/542b735819749.jpg",1657,1755);
$z[14][4]['name']="litpic";

?>