<?php
$z[0]=Array("field","生活大爆炸 第八季,生活大",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","7060手机电视剧为您提供《生活大爆炸 第八季》高清下载,《生活大爆炸 第八季》全集高清快播_百度影音在线观看下载,包含《生活大爆炸 第八季》3GP MP4下载,下载《生活大爆炸 第八季》",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","生活大爆炸 第八季",368,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","马克·森卓斯基",515,574);
$z[5][4]['name']="daoyan";
$z[6]=Array("field","2014 13:11",576,626);
$z[6][4]['name']="niandai";
$z[7]=Array("field","欧美",628,671);
$z[7][4]['name']="diqu";
$z[8]=Array("field","英语",673,717);
$z[8][4]['name']="yuuan";
$z[9]=Array("field","0",719,756);
$z[9][4]['name']="pfz";
$z[10]=Array("field","0",758,796);
$z[10][4]['name']="pfrs";
$z[11]=Array("field","CBS本年年除了《生活大爆炸》(The Big Bang Theory)外，其余的喜剧表现由还好至差劲（除了《老爸老妈的浪漫史》( How I Met Your Mother)），故此高层决定把《生活大爆炸》牢牢抓在手里，一口气续订了3季，所以《生活大爆炸》将至少播到2016-17年度季了。&nbsp;《生活大爆炸 第八季》电视剧全集下载百度影音在线观看由7060手机电影收集整理。",798,1279);
$z[11][4]['name']="juqing";
$z[12]=Array("field","",1281,1321);
$z[12][4]['name']="pubdate";
$z[13]=Array("field","吉姆·帕森斯,约翰尼·盖尔克奇,凯莉·库柯,西蒙·赫尔伯格,昆瑙·内亚,马伊姆·拜力克,梅丽莎·劳奇",1323,1493);
$z[13][4]['name']="zhuyan";
$z[14]=Array("field","http://p.tao30.com/Upload-s/video/2014-09/5425091b7ddaa.jpg",1495,1593);
$z[14][4]['name']="litpic";

?>